### PR TITLE
really 100 trace(a_n)'s

### PR DESCRIPTION
**Pull request by AndrewVSutherland**

### CODE REVIEW

**Comment by AndrewVSutherland** [comment]
mf_mfdecomp_full_100.m.txt checked against mf_mfdecomp_full_100.gp.txt, both have 100 traces everywhere and isomorphic fields but trace(a_1) in *.gp.txt is wrong (does not match degree) for 11:3:4, 17:2:4, 22:2:3, 23:2:3, 25:2:4, 29:2:4, 31:2:4, 34:2:4,33:2:5, 45:2:10.

**Comment by JohnCremona** [comment]
For the record, commit 0d84e783151b107d7473fa3e901baf36b8d08b73 fixed mfdecomp_full_100.gp.txt at about the time the previous comment was written;  and this PR seems to have deleted mfdecomp_full_100.txt by mistake.

**Comment by AndrewVSutherland** [comment]
That was intentional, I changed the name to .m.txt

On August 29, 2018 8:30:16 AM EDT, John Cremona <notifications@github.com> wrote:
>For the record, commit 0d84e783151b107d7473fa3e901baf36b8d08b73 fixed
>mfdecomp_full_100.gp.txt at about the time the previous comment was
>written;  and this PR seems to have deleted mfdecomp_full_100.txt by
>mistake.
>
>-- 
>You are receiving this because you modified the open/close state.
>Reply to this email directly or view it on GitHub:
>https://github.com/JohnCremona/CMFs/pull/8#issuecomment-416934894

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by AndrewVSutherland** [comment]
Whoops, the new file mfdecomp_full_100.m.txt was left out of this PR, but it is now there.

**Pull request merged**
